#daily market report 
#ask user to input necessary information about the market 
#print response on screen
market_name =input("Input the name of the market ")
Num_of_traders = input("How many traders are present in the market ")
Daily_rev = float(input("How much is made in total . i.e total revenue generated by the traders "))

print(f"\t{market_name} market\nNumber of traders\t{Num_of_traders}\nDaily revenue\t\t{Daily_rev:,} Naira")
